[package]
name = "wfc"
version = "0.1.0"
authors = ["cchudant <cchudant@student.42.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rand_chacha = "0.2.2"
image = "0.23.12"
